adding more errors to fix Concourse issue with unreliable cred mgrs
concourse/retryhttp pull request #4
Opened 2018-10-18 05:47 UTC by ralekseenkov

this is a first step towards fixing https://github.com/concourse/concourse/issues/2542

2018-10-18 05:47 UTC, pivotal-issuemaster commented
@ralekseenkov Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/retryhttp&pullRequestId=4)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/retryhttp&pullRequestId=4) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2018-10-18 05:47 UTC, pivotal-issuemaster commented
@ralekseenkov Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/retryhttp&pullRequestId=4)!

2018-10-18 05:48 UTC, ralekseenkov commented
@vito

2018-11-16 15:24 UTC, vito requested changes
Thanks! Just had a few questions inline.

2018-11-16 15:24 UTC, vito commented on retryer.go
> +	errors.New("connection reset by peer"),
This should be redundant; the `syscall.ECONNRESET` above has the same error message. Did that one not work?

2018-11-16 15:24 UTC, vito commented on retryer.go
> +	errors.New("handshake failure"),
Can you give an example of an error that returns this that we'd want to retry? At least with SSH, handshake failure usually means invalid credentials, which isn't retryable.

Can't think of anything else off the top of my head. Willing to pull it in, just curious what the error was.

2018-11-16 15:24 UTC, vito commented on retryer.go
> +	errors.New("handshake timeout"),
Makes sense to make this more general - I saw 'TLS handshake timeout' in concourse/concourse#2542.

2018-11-16 15:24 UTC, vito commented on retryer.go
> +	errors.New("timeout awaiting response headers"),
Makes sense too. Shame `net/http` doesn't export a var for this. Oh well.

2018-11-23 16:01 UTC, ralekseenkov commented on retryer.go
> +	errors.New("connection reset by peer"),
agreed

2018-11-23 16:02 UTC, ralekseenkov commented on retryer.go
> +	errors.New("handshake timeout"),
yes, exactly

2018-11-23 16:05 UTC, ralekseenkov commented on retryer.go
> +	errors.New("handshake failure"),
We've seen the following 4 with Vault and Volumes:
```
Finding variable 'consul_token': remote error: tls: handshake failure
Finding variable 'consul_token': Get [variable]: net/http: TLS handshake timeout
Finding variable 'aptomi_docker_registry_password': Get [variable]: dial tcp 13.77.xxx.xx:443: connect: connection reset by peer
Put /volumes/63f08caf-341b-411c-6036-90449cad3d36/stream-in?path=.: net/http: timeout awaiting response headers
```

The theory is that when your service runs on Kubernetes behind Azure LB, GKE LB, etc... these things sometimes happen.

2018-11-26 17:02 UTC, vito commented on retryer.go
> +	errors.New("handshake failure"),
Thanks. I guess we had it before, too (all the `remote error: handshake failure` Google results are TLS related). I'll go ahead and merge it. We're unlikely to use `retryhttp` for SSH handshaking so it shouldn't be very risky.

2018-11-26 17:02 UTC, vito approved these changes

2018-11-26 17:02 UTC, vito commented
thanks! (don't forget to bump `go.mod` in your PR, btw)

2018-11-26 17:02 UTC, merged